#!/usr/bin/env bash

NVIM_DIR=$HOME/.config/nvim/

install()
{

    plugin_path="$NVIM_DIR/pack/plugins/start"
    echo "$plugin_path"
    [[ -d "$plugin_path" ]] || mkdir -p "$plugin_path"
    cd "$plugin_path"

    while read plugin_link
    do
	git clone $plugin_link
    done < ../../../plugins.txt
}

update()
{
    cd "$plugin_path"
    for f in "$plugin_path"/*
    do
	cd "$f"
	git pull
    done 
}
