#!/usr/bin/env bash

##########
# ENVVAR #
##########

export EDITOR='nvim'
export PAGER='less'

###########
# ALIASES #
###########

alias sc='shellcheck'
alias acpi='echo $(cat /sys/class/power_supply/BAT0/capacity)%'

alias ls='ls --color=always --group-directories-first'

cdf()
{
    cd "$(fzf)" || exit
}

media()
{
    ffplay -nodisp -volume 100 -loglevel 0 "$1"
}

run()
{
    ("$@" &>/dev/null &)
}

setbr()
{
    echo "$1" | sudo tee /sys/class/backlight/"$2"/brightness
}

load_env()
{

}

#########
# $PATH #
#########

append_path()
{
    case ":$PATH:" in
        *:"$1":*) ;;
        *) PATH="${PATH:+$PATH:}$1"
    esac
}

prepend_path()
{    
    case ":$PATH:" in
        *:"$1":*) ;;
        *) PATH="$1${PATH:+$PATH:}"
    esac

}

append_path "$XDG_BIN_HOME"
append_path "$XDG_BIN_HOME"/vscode
append_path "$HOME"/.bin
append_path "$HOME"/.bin/jrider/bin
append_path "$HOME"/.bin/firefox

##########
# PROMPT #
##########

autoload -Uz promptinit && promptinit
prompt suse

###########
# STARTUP #
###########

case $TERM in 
    linux) clear && setfont -d;;
esac

########
# MISC #
########
