#!/bin/sh

export XCURSOR_THEME=Bibata
export XCURSOR_SIZE=16
export GTK_THEME=Adwaita:dark
export XCURSOR_THEME=elementary
export QT_QPA_PLATFORMTHEME=gtk3

picom -b
xwallpaper --zoom ~/.config/wlp.jpg
dunst &
nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }"
fcitx5 &
exec i3 -c ~/.config/uni3/i3.conf
