# vim: ft=i3config
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

# To get a config file with the same key positions, but for your current
# layout, use the i3-config-wizard

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 16

# Start XDG autostart .desktop files using dex. See also
# https://wiki.archlinux.org/index.php/XDG_Autostart
exec --no-startup-id dex --autostart --environment i3

# The combination of xss-lock, nm-applet and pactl is a popular choice, so
# they are included here as an example. Modify as you see fit.

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
exec --no-startup-id nm-applet

# use these keys for focus, movement, and resize directions when reaching for
# the arrows is not convenient
set $up l
set $down k
set $left j
set $right semicolon

set $XDG_CONFIG_HOME ~/.cfg

# use Mouse+Mod1 to drag floating windows to their wanted position
floating_modifier Mod1

# move tiling windows via drag & drop by left-clicking into the title bar,
# or left-clicking anywhere into the window while holding the floating modifier.
tiling_drag modifier titlebar

bindsym Mod1+Return exec kitty
bindsym Mod1+d exec dmenu_run
bindsym Mod1+Shift+q kill

# alternatively, you can use the cursor keys:
bindsym Mod1+Left focus left
bindsym Mod1+Down focus down
bindsym Mod1+Up focus up
bindsym Mod1+Right focus right

# alternatively, you can use the cursor keys:
bindsym Mod1+Shift+Left move left
bindsym Mod1+Shift+Down move down
bindsym Mod1+Shift+Up move up
bindsym Mod1+Shift+Right move right

# enter fullscreen mode for the focused container
bindsym Mod1+f fullscreen toggle

# toggle tiling / floating
bindsym Mod1+Shift+space floating toggle

bindsym Mod1+Shift+minus move scratchpad
bindsym Mod1+minus scratchpad show

set $term_ws "🖥️"
set $web_ws "🌐"
set $misc_ws "🧰"

bindsym Mod1+t workspace $term_ws
bindsym Mod1+b workspace $web_ws; layout tabbed
bindsym Mod1+m workspace $misc_ws

bindsym Mod1+Shift+t move container to workspace $ws1
bindsym Mod1+Shift+b move container to workspace $ws2
bindsym Mod1+Shift+m move container to workspace $ws3

mode "reset" {
		# reload config
		bindsym c reload

		# reload all
		bindsym a restart
}
bindsym Mod1+r mode "reset"

bindsym Mod1+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

gaps inner 10px
gaps outer 10px

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3blocks -c ~/.cfg/xorg/i3/blocks.conf
}
