xlibre-xserver xorg-xinit picom xwallpaper
i3-wm i3-blocks dmenu
wezterm 
aerc isync
helix vim
fd fzf ripgrep
bash dash 
clang rustup go

# manual installs:
# vscode
# antigravity
# nvm
# elvish & xonsh
